flathub/io.mpv.Mpv

io.mpv.Mpv.yml

- Remove `--enable-nonfree` ffmpeg build. This is not redistributable.
- Remove incompatible and unused `--enable-libfdk-aac` option.
- Switch luajit source to versioned branch as recommended by luajit upstream
- Add dependencies to enable mpv features.
What's missing:
- vapoursynth
- Best done by someone who can test this.
- vulkan + libplacebo
- Some deps require a new runtime
- libsixel
- To be done on next libsixel release

Fixes + enable extra mpv features 

---

io.mpv.Mpv.yml

This reverts commit 2cec20a464d8907529272b9276507ae28f4a8624.
That commit forced hard-coded non-default input bindings upon all users of this Flatpak package, which is a really bad and unexpected thing.
Imagine the user's surprise when they hit these cases despite `no-input-default-bindings`. This violates the principle of least surprise, and there's really no reason this needs to be done in this Flatpak...

Revert "enabled g,y forward/backward subtitle shortcuts"

---

io.mpv.Mpv.yml

Since mpv can now prefer yt-dlp over youtube-dl, (see https://github.com/mpv-player/mpv/pull/9209) this PR replaces youtube-dl with yt-dlp.
With the current version of the flatpak it's almost impossible to stream youtube videos (at least for me that's the case, it might depend on your IP address), as there's massive throttling. Also you cannot watch age-restricted videos with youtube-dl.
Both of these issues are worked around with yt-dlp.

Replace youtube-dl with yt-dlp

---

io.mpv.Mpv.yml

prevents screen blanking in GNOME (wayland) while playing media. fixes https://github.com/flathub/io.mpv.Mpv/issues/94

Include mpv_inhibit_gnome

---

io.mpv.Mpv.yml

The updated version links correctly to `libdbus`. Fixes #94.

Update mpv_inhibit_gnome to 0.1.2

---

io.mpv.Mpv.yml

This release fixes a crash on platforms where the GNOME inhibition protocol doesn't exist.
This might need to be published quickly.

Update mpv_inhibit_gnome to 0.1.3

---

io.mpv.Mpv.yml

This pull request enables [bs2b](https://bs2b.sourceforge.net/) on ffmpeg, which allows mpv to access it through the [audio filters option](https://mpv.io/manual/master/#options-af).
[The Bauer stereophonic-to-binaural DSP (bs2b) is designed to improve headphone listening of stereo audio records.](https://bs2b.sourceforge.net/)
Can be used with mpv by adding the [`--af=bs2b` option](https://mpv.io/manual/master/#audio-filters).
[Ffmpeg bs2b documentation.](https://ffmpeg.org/ffmpeg-filters.html#bs2b)
Additional information : https://hhsprings.bitbucket.io/docs/programming/examples/ffmpeg/manipulating_audio/bs2b.html

Enable Bauer stereophonic-to-binaural DSP on ffmpeg.

---

io.mpv.Mpv.yml

Updates libplacebo to latest version, this requires upgrading shaderc, which requires upgrading glslang.
Closes #148
Closes #150
Closes #151

Fixes #148 Broken video after libplacebo upgrade

---

io.mpv.Mpv.yml

SPIRV from Freedesktop 22.08 was too old, causing issues with script compilation with --vo=gpu-next --gpu-api=vulkan
Quote x265 tag, allows x-checker-data to function.
Fixes #156 vo/gpu-next/libplacebo errors
Closes #156

Build SPIRV from source.

---

README.md
io.mpv.Mpv.yml

Add mirror-urls for various sources. See #167
The git repo URI for libXmu was not updated anymore, use different URI.
Update libplacebo to v5.264.1
Update pytz to 2023.2
Update libXmu to 1.1.4
Fix wrong word in README.
Closes #167

Add mirror-urls, update modules.

---

io.mpv.Mpv.yml

https://github.com/flathub/io.mpv.Mpv/issues/159
disabled x-data-checker, till yt-dlp releases a fixed version which can play both audio and video from youtube.

Downgrade yt-dlp play audio

---

io.mpv.Mpv.yml

Constrains urrlib version for requests. https://github.com/psf/requests/issues/6432
Closes #188
Closes #189
Closes #190

Updates requests, dogpile

---

io.mpv.Mpv.yml

The external data checker was disabled in commit 3fdef98 because of mpv issue https://github.com/mpv-player/mpv/issues/11392, which was fixed in mpv 0.36.0.

Re-enable external data checker for yt-dlp

---

io.mpv.Mpv.yml

`yt-dlp` occasionally uses the `ffmpeg` binary, but since it is not build for the ffmpeg installation in `/app`, it uses the binary from the freedeskop runtime. This is undesirable, because this binary was built against older library versions, but when called, it partially uses the newer shared libraries in `/app/lib`. This is detected by `ffmpeg` and leads to the warning message:
`WARNING: library configuration mismatch`

Build ffmpeg programs

---

io.mpv.Mpv.yml
mpv

Currently mpv can only take a screenshot when user's directories are in English. This little wrapper will symlink `.var/app/io.mpv.Mpv/Pictures` to the `XDG_PICTURES_DIR`. It's a bit hacky, but better than the current situation.
Preferably, XDG user dirs should be added to mpv's config handler to substitute `~~pictures` etc. with an appropriate directory.

Save screenshots to xdg-pictures/mpv

---

io.mpv.Mpv.yml

Mesa regression is supposed to be fixed in 23.3.x (which is available in runtime): https://gitlab.freedesktop.org/mesa/mesa/-/issues/9922#note_2113862
Closes https://github.com/flathub/io.mpv.Mpv/pull/300
Closes https://github.com/flathub/io.mpv.Mpv/pull/262

Move to fsdk 23.08

---

io.mpv.Mpv.yml

Reverts flathub/io.mpv.Mpv#427
mpv 0.38 not detecting shaderc

Revert "build with spirv-header 4f74b4 and spirv-tools v2024.1"

---

io.mpv.Mpv.yml

- add mirrors to vidoelan.org (banned in india)
- disable shaderc not required on Linux https://github.com/mpv-player/mpv/issues/13940
- update mpv to 0.38.0

update mpv to 0.38.0 + disable shaderc for mpv + videolan.org mirrors

---

io.mpv.Mpv.appdata.xml
io.mpv.Mpv.yml

- vspipe not working with vapoursynth R69 or R70, but R60 works
- disabled -Dvulkan-interop for mpv v0.39.0 build to succeed

Update to v0.39.0

---

io.mpv.Mpv.yml

libgcrypt downgraded to 1.10.3 (to build for freedesktop 24.08)
vapoursynt R60 -> R70 (working flatpak run --command=vspipe io.mpv.Mpv --version)

Freedeskop 23.08 -> 24.08

---

io.mpv.Mpv.yml

All of those should work ootb in 24.08 runtime. Previously shaderc and some parts of vulkan were missing which created incompatibilities between parts versions shipped in app and in runtime but now it should be finally ok.

Drop deps that are avalaible in runtime

---

io.mpv.Mpv.yml

The build is failing with cryptic error. It should be investigated and fixed separately without blocking rest of updates.

Disable updates for mujs
